### ISSUE TITLE
 Not working from console

### ISSUE THREAD

**Issue by sasha-id** [chadrem/tribe#1]
Working fine from irb, but when execute test script (your example from README) in console `ruby test.rb`, no output.

**Comment by chadrem** [comment]
@alex-klepa Tribe doesn't block the main thread so it sounds like the main thread is exiting before your actors are doing any work. When then main thread ends, the Ruby process exits even if there are other threads doing work. You will need to block the main thread yourself. A simple solution you can put at the bottom of your script:

```Ruby
while(true) do
  sleep 1
end
```

Since Tribe doesn't block the main thread, you can easily integrate Tribe into other frameworks (such as Rails) or other scripts. This is a design feature to give you control.

If this doesn't solve your problem then I'll need to see your script.

**Comment by sasha-id** [comment]
You are right, my bad ;) Working perfectly!

**Comment by chadrem** [comment]
I’ll leave this issue open until I have time to add that loop to the docs. Thanks for pointing it out.

**Comment by chadrem** [comment]
I've updated the docs for both gems (Tribe and Workers) to mention main thread issue:

https://github.com/chadrem/tribe#rubys-main-thread
